# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: gh-pages
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:  ${{ secrets.ftp_server }}
        username:  ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
