name: Gatsby Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
        env:
          GA_TRACKING_ID : ${{ secrets.GA_TRACKING_ID }}
          C_API_URL : ${{ secrets.C_API_URL }}
          C_API_URL_MAIL : ${{ secrets.C_API_URL_MAIL }}
          C_URL : ${{ secrets.C_URL }}
